runtime: go
api_version: go1
application: scraper-155718
version: dev
automatic_scaling:
  max_concurrent_requests: 200

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /.*
  script: _go_app
